host: 127.0.0.1
port: 8080
timeout: 5
scheme: http://
mongodb:
    host: 39.106.144.46
    port: 27017
    user:
    password:
log:
    file_name: test.log
    backup: INFO
    console_level: DEBUG
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
adv:
    host: 10.50.4.115
    port: 8080
    timeout: 5
    scheme: http://